version: "3.8"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: safer_ride_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safer_ride
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data           # <â€” named volume
      - ./init:/docker-entrypoint-initdb.d  
            # init scripts

volumes:
  pgdata:                                         # declared here
